version: '3.7'

x-postgres-creds: &postgres-creds
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: personal-site-db

services:
  api:
    build:
      context: ./api
    command: ['npm', 'start']
    environment:
      NODE_ENV: development
      PORT: 4000
      POSTGRES_HOST: postgres
      SESSION_SECRET: dev-secret
      REDIS_HOST: redis
      <<: *postgres-creds
    ports:
      - 4000:4000
    depends_on:
      - postgres
      - redis
    volumes:
      - ./api/src:/app/src

  postgres:
    image: postgres:10.7-alpine
    environment:
      <<: *postgres-creds
    ports:
      - 5432:5432
    restart: 'always'
    volumes:
      - personal_site_postgres_db:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    restart: 'always'
    volumes:
      - ./redis-data:/data

volumes:
  personal_site_postgres_db:
